src/objects/Agreement__c.object
<CustomObject>
    <fields>
        <fullName>Agreement_Template__c</fullName>
        <label>Agreement Template</label>
        <referenceTo>Template__c</referenceTo>
        <relationshipLabel>Agreements</relationshipLabel>
        <relationshipName>Agreements</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Recipient__c</fullName>
        <label>Recipient</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Agreements</relationshipLabel>
        <relationshipName>Agreements</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Agreement</label>
    <nameField>
        <label>Agreement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agreements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Template__c.object
<CustomObject>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>NDA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Quote</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Order</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Employee Offer Letter</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Addendum</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Agreement Template</label>
    <nameField>
        <label>Content Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agreement Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/AgreementTriggerHandler.cls
public with sharing class AgreementTriggerHandler {
	private boolean m_isExecuting = false;
	private integer BatchSize = 0;
	
	public AgreementTriggerHandler(boolean isExecuting, integer size){
		m_isExecuting = isExecuting;
		BatchSize = size;
	}
	
	public void OnBeforeInsert(Agreement__c[] newAgreements){
		Map<id,Template__c> templateMap = new Map<id,Template__c>([SELECT Id,Name, Type__c, Content__c FROM Template__c limit 50000]);
		
		//TODO: Dynamic merge templating.
		/* move to preview button
		 * 
		 */  
		for(Agreement__c newAgreement : newAgreements){
			Template__c template = templateMap.get(newAgreement.Agreement_Template__c);
			if(template != null && template.Content__c != null && template.Content__c != ''){
				newAgreement.Content__c = template.Content__c;
			}
		}
	}
	/*
	public void OnAfterInsert(Agreement__c[] newAgreements){}
	
	@future public static void OnAfterInsertAsync(Set<ID> newAgreementIDs){}
	
	public void OnBeforeUpdate(Agreement__c[] oldAccounts, Agreement__c[] updatedAccounts, Map<ID, Agreement__c> agreementMap){}
	
	public void OnAfterUpdate(Agreement__c[] oldAccounts, Agreement__c[] updatedAccounts, Map<ID, Agreement__c> agreementMap){}
	
	@future public static void OnAfterUpdateAsync(Set<ID> updatedAgreementIDs){}
	
	public void OnBeforeDelete(Agreement__c[] accountsToDelete, Map<ID, Agreement__c> agreementMap){}
	
	public void OnAfterDelete(Agreement__c[] deletedAccounts, Map<ID, Agreement__c> agreementMap){}
	
	@future public static void OnAfterDeleteAsync(Set<ID> deletedAgreementIDs){	}
	
	public void OnUndelete(Agreement__c[] restoredAgreements){}
	*/
	
	public boolean IsTriggerContext{
		get{ return m_isExecuting;}
	}		
	
	public static testMethod void tests(){
		Template__c template = new Template__c();
		insert template;
		
		Contact c = new Contact();
		c.FirstName = 'first';
		c.LastName = 'last';
		insert c;
		
		Agreement__c agreement = new Agreement__c();
		agreement.Agreement_Template__c = template.Id;
		agreement.Recipient__c = c.Id;
		insert agreement;
		
		List<Agreement__c> agreementList = new List<Agreement__c>();
		agreementList.add(agreement);
		
		AgreementTriggerHandler handler = new AgreementTriggerHandler(true, 100);
		
		handler.OnBeforeInsert(agreementList);
		
		System.assertEquals(true, handler.IsTriggerContext);
	}
}